### ISSUE TITLE
[iOS 12.5.6] Cannot add sample folders

### ISSUE THREAD

**Issue by gstepniewski** [elf-audio/Koala-Bugs#11]
On an older iPad Air with iOS 12.5.6, pressing the Add Location button opens a dialog with the file browser, but there is no way to actually select a folder - the only action button available is "Cancel".

![IMG_A8A5BB48DD20-2](https://github.com/elf-audio/Koala-Bugs/assets/424327/813a99f9-3940-4388-a86c-301e3d0ffd0c)

I know it's a long shot and possibly impossible to fix because of no APIs in older iOS, but maybe there's a fix or a workaround?

**Comment by mazbox** [comment]
Unfortunately koala doesn't support adding folders in 12.5 - as you say,
it's something only made available by apple in iOS 14 - I should probably
disable the button for previous versions but the number of users below iOS
14 is something like 1% of total users. Really sorry about that!

**Comment by gstepniewski** [comment]
Well I guess it's time to get a newer iPad then ¯\\_(ツ)_/¯

Thanks for the reply, closing the issue!
