### ISSUE TITLE
NOTE REPEAT pitch scroll command is buggy after updating Koala.

### ISSUE THREAD

**Issue by 774no5nbe** [elf-audio/Koala-Bugs#13]
NOTE REPEAT pitch scroll command is buggy after updating Koala. 

I use a HUAWEI smartphone.  Android version is 10.  Koala's version is 1.4072 (SAMURAI).  

It didn't improve even after restarting the terminal or deleting the Koala cache.  
Koala is my best app！please fix the bug.

![Videoframe_20230517_032110_com huawei himovie overseas](https://github.com/elf-audio/Koala-Bugs/assets/133805367/2ce9a688-265a-4e65-aaa1-4584cb5ff5d7)

**Comment by mazbox** [comment]
Thanks for reporting - this is fixed for the next version
