### ISSUE TITLE
Stretch function not applying after normalizing samples

### ISSUE THREAD

**Issue by MikeAnt26** [elf-audio/Koala-Bugs#14]
If you click on the stretch button after you normalize a sample the stretch function doesn’t apply to the sample.

I’m running Koala on an iPhone 8 Plus on iOS version 15.6.1

**Comment by mazbox** [comment]
does this happen every time you normalise then try to stretch a sample or just sometimes?

**Comment by mazbox** [comment]
Can I ask, does the STRETCH button press down or does it stay up? Do you get the little bar at the top saying "4 BEATS" or whatever the duration is? Any more info would be super helpful! I can't seem to recreate this.

**Comment by MikeAnt26** [comment]
> Can I ask, does the STRETCH button press down or does it stay up? Do you get the little bar at the top saying "4 BEATS" or whatever the duration is? Any more info would be super helpful! I can't seem to recreate this.

I’m running iPhone 8 Plus on iOS 15.6.1 and iPhone SE 2nd Gen on iOS 16.3

I can replicate the issue in Koala running on both devices every time. The steps to find the bug are as follows: you have to normalize before using the stretch function. After you normalize when you stretch nothing happens. The drop down menu doesn’t appear and it doesn’t stretch the sample. To get it working again you have to hit the pad with the sample that was normalized.
