### ISSUE TITLE
Additional .kpk files placed in the 'packs' folder are not recognized

### ISSUE THREAD

**Issue by gstepniewski** [elf-audio/Koala-Bugs#27]
This is probably more of a feature request in disguise than a bug, but I think it would be a great feature if additional zip files with samples inside were recognized by Koala and added to the samples browser.
It would be especially helpful on older iOS devices where folder mapping does not work and loading samples one by one (without a way to preview them!) is a massive pain.

**Comment by PaulChana** [comment]
This is an area we are currently actively working on (and it's a deep rabbit hole), so im going to close this issue for the moment. Once we have the work done and out in the wild, we can revisit. 
Thanks for the report
