### ISSUE TITLE
Autochop equal limited to 16 chops

### ISSUE THREAD

**Issue by mgerber23** [elf-audio/Koala-Bugs#32]
Auser identified a regression. If you choose a sound and autochop equal, you can only go up to 16 slices. I remember you used to be able to choose 64 and fill up every pad so I’m feeling fairly confident this used to go up to 64. Also lazy and transients chop allow you to go up to 64 so it def seems broken.

**Comment by mazbox** [comment]
I think it was always 16 - the main reason being that the slider becomes unmanageable when there are 64 divisions and 16 is a good practical limit - I might change this in the future but I think 16 is ok. I guess you could do an equal chop of 4, then 4 sets of 16?
