### ISSUE TITLE
"Show file names on pads" sometimes writes something that is not the filename in android

### ISSUE THREAD

**Issue by mazbox** [elf-audio/Koala-Bugs#34]
I've been having an issue in regarding the function of "Show file names on pads". The app doesn't show the actual file names of the imported third party samples. It names them with something like "primary%...etc." But if the imported samples are from BASICS, the app does name them correctly.

**Comment by gstepniewski** [comment]
Another slight annoyance that, as far as I can tell, happens on Android only is that when you go to edit the pad label the text field is empty.
