### ISSUE TITLE
Auto-chop wrapping problem

### ISSUE THREAD

**Issue by mazbox** [elf-audio/Koala-Bugs#4]
Steps to reproduce:
1. Long sample in D9
2. Select Edit, Tools, Auto Chop
3. Select equal, and slider to 8 chops, one-shot enabled, keep original and other options disabled (no choke group)
4. After hitting chop button, samples go to first open slots (B2-B8, expected them to fill D9-D16). 
5. First auto chopped sample was placed on slot A1 replacing the sample that was already there.

Workaround is to move long sample to slot B9. The chopped samples fell in the range B9-B16 as expected)

**Comment by AldoMosca** [comment]
Subscribed. Let me know if you need anything else.

**Comment by mazbox** [comment]
ah thanks again! should be an easy fix.

**Comment by PaulChana** [comment]
This was fixed a few versions ago
