### ISSUE TITLE
Split Stems issue

### ISSUE THREAD

**Issue by arfo62** [elf-audio/Koala-Bugs#40]
Hi everyone,
I’m trying to use the split stems function on my 2021 MacBook Pro M1 max 16” but it doesn’t work…
I tried a reinstall from App Store but with no results.
Everything ok with the same function on iPad8.
Thank you for helping!
Art

**Comment by mazbox** [comment]
This feature is not currently supported by koala on Mac. I want to support it but its a lot of work and koala on Mac is free, so for now, pls just use the one on your phone or install the iOS version of koala on your Mac and use that.

**Comment by arfo62** [comment]
Hi @mazbox,
thank you for answering so quickly and for your wonderful app, that I like very much; I can guess how much work it’s needed so that’s ok for me.
I didn’t know it’s possible to install an IOS app on a common laptop, how could I do?
I can use the iPad one anyway.
Best wishes,
Art

**Comment by mazbox** [comment]
Here’s how to do it:
https://uk.pcmag.com/iphone-apps/145810/ios-on-macos-how-to-run-iphone-and-ipad-apps-on-your-mac


All the best

Marek
https://www.elf-audio.com
