### ISSUE TITLE
Cannot import Koala songs

### ISSUE THREAD

**Issue by garochik** [elf-audio/Koala-Bugs#41]
Hello

Since I have changed my phone, I am not able to import my koala songs exported with my previous device anymore. When I click on menu, load, import, nothing happens. No file browser shows up.

Operating system (and version) Android 14 - OneUI 6.1 
Device Samsung S24 ultra
Are you using it with any hardware? No
Do you have any third party software running that might be interfering with koala? No
Koala version? 1.4081 Samurai
How much free storage do you have left? More than 400gb
Steps to reproduce the problem : menu, load, import

May be linked with the new CPU snapdragon 8 gen 3? 

Thank you

**Comment by PaulChana** [comment]
Sounds like a problem with permissions. If you are still having this problem, please contact support and we can help you
