### ISSUE TITLE
Issues with QWERTY mappings in Android

### ISSUE THREAD

**Issue by gstepniewski** [elf-audio/Koala-Bugs#42]
Little bit of UX feedback first:

* It would be nice to see which file is currently loaded, in case someone uses multiple mappings for different devices
* Perhaps more importantly, it would be very useful to be able to go back to the default. I have done an export and modified it without backing up and now it seems like the only way of resetting it is clearing app data?

As for the feature itself, some of the events don't seem to work properly:

<table>
<tr>
 <td>PREV_SECTION
 <td>Doesn't seem to work either as 'shift-tab' or when mapped to something else, e.g. "\u0001`".
<tr>
 <td>SEQUENCE_PREV_BANK<br>SEQUENCE_NEXT_BANK
 <td>These both scroll through pad banks instead
<tr>
 <td>SEQUENCE_DOUBLE_UP
 <td>Worked on default mapping (although it was = to double up and + to increase, unlike what the help website says), but when remapped to be the opposite (+ to double up and = to increase) they now both just increase
<tr>
<td>DELETE_CURR_SAMPLE<br>SHOW_MEDIA_BROWSER
<td>Can't get these to work, either as default or when remapped to a different key ('|')
<tr>
</table>

Also it doesn't seem possible to remap pads and sequences? I tried making a mapping for landscape mode with pads on A-K/Z-, and sequences on 3-6/E-Y but they refuse to move over. [Here](https://github.com/elf-audio/Koala-Bugs/files/14936886/keyboard-land.json) is the file I tried using.

Let me know if there is anything I could to be of more help - this feature is one of my favourites in a long time, it really lifts the app onto Ableton Live levels of customisability and I would love to help iron it out fully!

**Comment by PaulChana** [comment]
Hi, Ive fixed these now - fixes should be coming in a future update to Koala. Thanks for the bug report
