### ISSUE TITLE
Visual glitch in piano roll

### ISSUE THREAD

**Issue by pfortythree** [elf-audio/Koala-Bugs#43]
iPad Pro 11 (Gen4) A2759
iPadOS 17.6.1
Koala sampler v.1.4091 (6144) (Samurai + Mixer)
Also i was able to reproduce it at iPhone 15 A3090 with iOs 18.0 (version of Koala app the same as on iPad)
But on iPad (5 Gen) A1822 with iPadOS 16.7.10 and same version of Koala app this bug does not appear
Free storage is enough on every device that i use in this case (more than 5 GBs on each)
This bug appears both - when I transfer the same project between devices and when i create a new project without the same files from old project. This bug more applies for piano roll and midi notes ("blocks") appears  on it, than audio files on pads of koala sampler app.
So, i`m creating 60 bar sequence in order to create automatic activation clips cuted on pads, zooming in by two fingers gesture for precise control position of midi "cubes", however at some moment the “cubes” simply disappear (at a some stage of enlargement). Also they jump back and forth by a millimeter when the piano roll moves, and it is not clear whether they are already set correctly or not.
It seems that this manifests itself specifically in long sequences; I haven’t noticed this before when creating 8-16 bar seq.
![tgfbffe1916f](https://github.com/user-attachments/assets/5504650c-033c-4468-a1ec-ad9b9cdf42f6)

**Comment by mazbox** [comment]
this is fixed for the next version, thx a lot for reporting!
