### ISSUE TITLE
MIDI monitor window goes blank after minimizing on Android

### ISSUE THREAD

**Issue by gstepniewski** [elf-audio/Koala-Bugs#45]
The MIDI monitor goes blank after the app is minimized and then brought back.
- it doesn't matter if the window is open when the app is being minimized
- minimizing again has no effect, the only way to fix it is killing the app
- it doesn't matter how many MIDI pads I have, when it breaks it breaks for all of them
- reproducing consistently on Pixel 9 Pro with Android 15, I can try some other devices if needed

**Comment by mazbox** [comment]
fixed for next release, thx for reporting. OpenGL on android is an unforgiving swine.
