### ISSUE TITLE
[BUG] Cancelling 'replace FX' in mixer removes current FX

### ISSUE THREAD

**Issue by mikobuntu** [elf-audio/Koala-Bugs#46]
Bug present in my 2 available platforms:- Android and Linux

steps to reproduce:-

(1) Add or choose any already loaded FX plugin in the Mixer.
(2) Select any FX and choose 'Replace' from the drop down burger menu.
(3) Now cancel the 'Replace' option by clicking 'X' at the top right of the FX list.

What happens:-

The FX plugin is completely deleted, it should instead keep the FX plugin that was already there. ( see video )

https://github.com/user-attachments/assets/52c7228d-2a1e-4a67-bdf6-f185019ac303

**Comment by PaulChana** [comment]
Thanks for the report. Fix will be in an upcoming release
