### ISSUE TITLE
Quokka must reset the LFO's upon pressing play.

### ISSUE THREAD

**Issue by Pensegi** [elf-audio/Koala-Bugs#47]
Hi! Quokka is REEEEAALLY nice!! There is just one thing: there needs to be a way to reset the LFOs. For instance upon pressing play. Otherwise the sound is VERY unpredictable, especially on long and deep LFOs. 😉👍

**Comment by Pensegi** [comment]
At least to have this as an option

**Comment by Pensegi** [comment]
It could also reset per note played as an option

**Comment by Pensegi** [comment]
I guess some will also want the unpredictability as a creative option, so perhaps make the reset an option to select: None, note, sequence or play

**Comment by Pensegi** [comment]
https://github.com/user-attachments/assets/7f0a3e63-06cd-4a85-b975-a55c309346c0

**Comment by mazbox** [comment]
Hi. This is a feature request, not a bug as far as I can tell. The lack or lfo reset is intentional. It's not to everyone's taste but it works as expected. Your feature request is logged, thanks!
