### ISSUE TITLE
Tools menu out of place

### ISSUE THREAD

**Issue by judyshatkin** [elf-audio/Koala-Bugs#7]
https://www.facebook.com/reel/1279441519313761?fs=e&s=TIeQ9V&mibextid=0NULKw

**Comment by mazbox** [comment]
From a user: "The best way i found to recreate this would be to rapidly keep pressing a sample pad  and while doing this simultaneously press the tool button. I also wanted to mention that doing this same thing but while on the sequence page and pressing the tempo button along with rapidly pressing a sample pad causes the tempo options to disappear completely"

**Comment by mazbox** [comment]
https://user-images.githubusercontent.com/194121/232914867-677e893f-0ae7-49a4-bf8d-c6edea4db2ff.mov

**Comment by mazbox** [comment]
fixed for release after next
